# Pull the Node image from Docker Hub
FROM node:lts

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm install

# Copy rest of the code to container
COPY . .

ENTRYPOINT ["npm", "run"]


