version: '3.8'
services:
  nextjs-ui:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    container_name: nextjs-ui
    stdin_open: true
  node_db:
    container_name: node_db
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nabil
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=pg_db
    volumes:
      - db:/var/lib/postgresql/data
  node_backend:
    container_name: node-api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3080:3080"
    environment:
      - EXTERNAL_PORT=3080
      - PGDATABASE=pg_db
      - PGUSER=nabil
      - PGPASSWORD=12345
      - PGHOST=node_db
      - DB_PORT=5432
      - JWT_SECRET=adafafdwfwrw1
      # - NODE_ENV=development
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
      - /usr/src/app/api/node_modules/bcrypt
    depends_on:
      - node_db

volumes:
  db:
    driver: local
