version: '3.8'
services:
  nextjs-ui:
    build:
      context: .
    ports:
      - "3001:3001"
    container_name: nextjs-ui
    stdin_open: true
    volumes:
      - ./my-app:/usr/src/app/client
      - /usr/src/app/client/node_modules
  node_backend:
    container_name: node-api
    build:
      context: .
    ports:
      - "3080:3080"
    environment:
      - EXTERNAL_PORT=3080
      - PGDATABASE=pg_db
      - PGUSER=nabil
      - PGPASSWORD=12345
      - PGHOST=node_db
      - DB_PORT=5432
      - JWT_SECRET=adafafdwfwrw1
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=nabil
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=pg_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
